### ISSUE TITLE
Implement state and DB handling mechanism

### ISSUE THREAD

**Issue by erik-edling** [eiffel-community/eiffel-gerrit-plugin#12]
### Description

Dependent on #8 

The eiffel events should be able to ask the state handling mechanism about the eiffel id for a specific link type by providing some input(to be decided in this story) in order for the state handler to know the current context for the link(branch etc).

This story also includes implementation of the DB handling mechanism where all the eiffel event IDs are stored. It should be possible to save and retrieve eiffel event ids. 

Please see #6 for the architectural overview document.

**Comment by m-linner-ericsson** [comment]
Would this text add more information to the issue or is it too detailed?

Input:
- Gerrit event
- Eiffel event
- Storage location

Outputs:
- Previous event id

Public interface:
- Get previous id
- Store Eiffel event

Error handling:
- Store fails
- Read fails

Possible usage:
```
StateHandler stateHandler = new StateHandler(storageLocation);

// Get previous id
stateHandler.getPreviousEiffelEventId(gerritEvent);

// Store events
stateHandler.storeEiffelEvent(eiffelEvent);
```

**Comment by a-breid-ericsson** [comment]
In this case it may be too detailed since the person investigating the issue maybe should present input, output and interfaces.

**Comment by m-linner-ericsson** [comment]
Just noticing that this will limit the amount of people being able to help out...
