### ISSUE TITLE
Provide an UI for Gerrit to configure Eiffel Message sending enabled and REMReM configurations

### ISSUE THREAD

**Issue by SantoshNC68** [eiffel-community/eiffel-gerrit-plugin#2]
Dependent on #8 

Investigate what configurations the GUI should provide with regards to the architecture overview seen here #6. Some configurations that should exist at minimum is:
- The enabling of event sending
- REMReM configuration
- Selection of which events you want to trigger on

**Comment by magnusbaeck** [comment]
Are you targeting PolyGerrit, the legacy GWT UI, or both?

**Comment by SantoshNC68** [comment]
At present it will be Legacy GWT UI then the changes will be added on top if it is non compatible.
