### ISSUE TITLE
Multi-valued configuration key inconsistencies

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/eiffel-gerrit-plugin#34]
### Description
The plugin documentation in [src/main/resources/Documentation/about.md](https://github.com/eiffel-community/eiffel-gerrit-plugin/blob/master/src/main/resources/Documentation/about.md) describes two different ways of dealing with multi-valued configuration keys:

* The `filter` key uses spaces to separate the branch name regexps.
* The `flow-context` key uses commas to separate message UUIDs.

The configuration file format (and the [PluginConfig](https://gerrit.googlesource.com/gerrit/+/7b2f4ccb46f22c97c07af4cbf5f310181064f284/gerrit-server/src/main/java/com/google/gerrit/server/config/PluginConfig.java) accessor API) supports multi-valued keys:

```
[plugin "eiffel-integration"]
  enabled = true
  filter = (release-).*
  filter = master
  flow-context = 971da14a-20cb-46f4-bf8f-86bb9f556499
  flow-context = 4914ed1b-15e6-48cf-9cff-841fb0c4d800
  remrem-publish-url = <URL of REMReM publish service>
  remrem-username = <REMReM Username to authenticate>
  remrem-password = <Password for the above user>
```

### Motivation

Inconsistencies in how the plugin in configured is clearly undesirable and increases the risk of misconfiguration. An incorrect configuration in this plugin can be especially problematic since it could lead to message loss which is hard or at least annoying to fix after the fact.

Apart from the consistency argument, dealing with multi-valued keys in the standard way makes it easier for automation. For example, [git-config(1)](https://git-scm.com/docs/git-config) supports multi-valued keys and it's totally conceivable that one would want to bulk-edit project.config files in many projects to e.g. add or remove a branch filter or flow context ID.

**Comment by SantoshNC68** [comment]
How does the multi-valued keys effect the general gerrit configurations? Is it just with eiffel configurations that we see inconsistencies?

**Comment by magnusbaeck** [comment]
> How does the multi-valued keys effect the general gerrit configurations? Is it just with eiffel configurations that we see inconsistencies?

The inconsistency is that the Gerrit plugin uses spaces to separate multiple `filter` values and commas for multiple `flow-context` values.

> I tried editing the project description and it allows and overrides the last set value:

Yes, unless you specifically ask for all values with getStringList(). Example with git-config(1), which I assume behaves like PluginConfig:

```
$ git config -f test.config foo.bar value1
$ git config -f test.config --add foo.bar value2
$ cat test.config 
[foo]
	bar = value1
	bar = value2
$ git config -f test.config foo.bar             
value2
$ git config -f test.config --get-all foo.bar 
value1
value2
```

**Comment by SantoshNC68** [comment]
> > How does the multi-valued keys effect the general gerrit configurations? Is it just with eiffel configurations that we see inconsistencies?
> 
> The inconsistency is that the Gerrit plugin uses spaces to separate multiple `filter` values and commas for multiple `flow-context` values.
> 
> > I tried editing the project description and it allows and overrides the last set value:
> 
> Yes, unless you specifically ask for all values with getStringList(). Example with git-config(1), which I assume behaves like PluginConfig:
> 
> ```
> $ git config -f test.config foo.bar value1
> $ git config -f test.config --add foo.bar value2
> $ cat test.config 
> [foo]
> 	bar = value1
> 	bar = value2
> $ git config -f test.config foo.bar             
> value2
> $ git config -f test.config --get-all foo.bar 
> value1
> value2
> ```

Ok, so the inconsistencies you want to resolve by using any one type either go with spaces or with commas.
On the other way of setting values, yes that can be resolved with getStringList() instead of getString().

**Comment by SantoshNC68** [comment]
Merged the changes and closing the issue.
