### ISSUE TITLE
Eiffel gerrit plugin overview

### ISSUE THREAD

**Issue by erik-edling** [eiffel-community/eiffel-gerrit-plugin#6]
### Description

In order to get an overview of the scope of the implementation there should be an architectural overview of the different components and how they fit together(Not in the detail of input/output). This overview will then be used to create the rest of the stories for the actual implementation.

Note that we want to work agile so do not make the overview too detailed as requirements might change.
### Motivation

In order to paralellize the work to different people we will need some kind of overview. This will help us have a somewhat clear picture of what we are to implement.

**Comment by e-edling-ericsson** [comment]
We have a first draft of the architectural overview and how the different parts of the gerrit plugin could communicate.

[gerrit-plugin-detailed.pdf](https://github.com/eiffel-community/eiffel-gerrit-plugin/files/3615922/gerrit-plugin-detailed.pdf)

**Comment by erik-edling** [comment]
I will close this issue as it is no longer relevant.
