### ISSUE TITLE
The Gerrit Plugin should be able to send EiffelSourceChangeCreatedEvent and EiffelSourceChangeSubmittedEvent

### ISSUE THREAD

**Issue by e-edling-ericsson** [eiffel-community/eiffel-gerrit-plugin#7]
### Description

Dependent on #8 

The first draft of the gerrit plugin should be able to send EiffelSourceChangeCreatedEvent and EiffelSourceChangeSubmittedEvent. According to #6 there should be some kind of mechanism to generate the Eiffel events. The factory pattern could be one such way to realize this in order to make the one generating the event less affected by future additions/changes.

On initialization of the Eiffel event, it should populate itself with relevant fields from the gerrit event(besides from the links).

As a summary, this story should implement the functionality to generate Eiffel events as well as creating the actual EiffelSourceChangeCreatedEvent and EiffelSourceChangeSubmittedEvent object.

Please see #6 for the architectural overview document.

**Comment by m-linner-ericsson** [comment]
Would this text add more information to the issue or is it too detailed?

Input:
- Gerrit event
- Database connection
- RemRem connection

Public interface:
- Create a new event
- Send the event

Error handling:
- Database store fails
- RemRem fails to send or doesn't respond

Possible usage:
```
EiffelEvent eiffelEvent = EventFactory.create(gerritEvent, databaseHandle);
effielEvent.send(remRemHandle);
```

**Comment by e-edling-ericsson** [comment]
I think it's great, thank you :)

**Comment by e-edling-ericsson** [comment]
I wont have any progress for a while as I've gotten other internal priorities.
